kind = "web"
previewPath = "/"
title = "TalentSphere"
version = "1.0.0"
id = "artifacts/talent-sphere"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19148

[services.development]
run = "pnpm --filter @workspace/talent-sphere run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/talent-sphere", "run", "build" ]
publicDir = "artifacts/talent-sphere/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19148"
BASE_PATH = "/"
